version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD=changeme           # Set the default password for the 'elastic' user
    ports:
      - "9200:9200"                         # Expose Elasticsearch HTTP port
      - "9300:9300"                         # Expose Elasticsearch transport port
    volumes:
      - es-data:/usr/share/elasticsearch/data  # Persist data in a named volume

volumes:
  es-data:
    driver: local
